services:
  bitcoind:
    image: kylemanna/bitcoind:latest
    container_name: bitcoind
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${BITCOIND_DATA_PATH:-/srv/bitcoin}:/bitcoin
    ports:
      - "8332:8332"
      - "8333:8333"

  ckpool:
    image: ghcr.io/jamestrichardson/ckpool-docker:latest
    container_name: ckpool
    restart: unless-stopped
    depends_on:
      - bitcoind
    env_file: .env
    volumes:
      - ${CONFIG_PATH:-/srv/ckpool/config}:/config
    ports:
      - "3333:3333"
    environment:
      # These override .env defaults to ensure they work within the compose network
      BTC_RPC_URL: bitcoind:8332
      BTC_RPC_USER: ${BTC_RPC_USER}
      BTC_RPC_PASS: ${BTC_RPC_PASS}
